databases:
  - name: tuteur-db
    databaseName: tuteur_intelligent
    user: tuteur_user
    plan: free

services:
  # 1. API BACKEND (Django)
  - type: web
    name: tuteur-backend
    env: python
    pythonVersion: "3.12.8"
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python create_admin.py && python init_data.py && python manage.py loaddata data_export.json"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tuteur-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: FRONTEND_URL
        #  le lien vers  frontend hébergé sur Vercel
        value: "https://tuteur-intelligent.vercel.app"
      - key: PYTHON_VERSION
        value: "3.12.8"
      # ⚠️ Secrets à ajouter MANUELLEMENT dans le dashboard Render :
      # - GROQ_API_KEY
      # - EMAIL_HOST_PASSWORD
      # - EMAIL_HOST_USER
      # - EMAIL_HOST
      # - EMAIL_PORT
      # - EMAIL_USE_TLS
      # - DEFAULT_FROM_EMAIL
